
console.log("JS Connected");
// variables
// let button_6 = document.querySelector("#button_6")
// let Arrbutton = [document.querySelector("#button_5"),document.querySelector("button_6")]
    //  button_5,button_6,button_7,button_8,button_9,button_10,button_11,button_12,];
// console.log(Arrbutton);

// orderNow JS 

let button_5 = document.querySelector("#button_5");
button_5.addEventListener ('click',function(){

    button_5.style.color = "#fff";
    button_5.style.backgroundColor = "red";
    button_5.style.border = "red";
});


let button_6 = document.querySelector("#button_6");
button_6.addEventListener ('click',function(){

    button_6.style.color = "#fff";
    button_6.style.backgroundColor = "red";
    button_6.style.border = "red";
});

let button_7 = document.querySelector("#button_7");
button_7.addEventListener ('click',function(){

    button_7.style.color = "#fff";
    button_7.style.backgroundColor = "red";
    button_7.style.border = "red";
});

let button_8 = document.querySelector("#button_8");
button_8.addEventListener ('click',function(){
    button_8.style.color = "#fff";
    button_8.style.backgroundColor = "red";
    button_8.style.border = "red";
});

let button_9 = document.querySelector("#button_9");
button_9.addEventListener ('click',function(){

    button_9.style.color = "#fff";
    button_9.style.backgroundColor = "red";
    button_9.style.border = "red";
});

let button_10 = document.querySelector("#button_10");
button_10.addEventListener ('click',function(){

    button_10.style.color = "#fff";
    button_10.style.backgroundColor = "red";
    button_10.style.border = "red";
});

let button_11 = document.querySelector("#button_11");
button_11.addEventListener ('click',function(){

    button_11.style.color = "#fff";
    button_11.style.backgroundColor = "red";
    button_11.style.border = "red";
});

let button_12 = document.querySelector("#button_12");
button_12.addEventListener ('click',function(){

    button_12.style.color = "#fff";
    button_12.style.backgroundColor = "red";
    button_12.style.border = "red";
});

// input Name

// HIDE AND show subcribe btn BUTTON Code
